spring.application.name=kantraspring

#configuration de la base de donnée
spring.datasource.url=jdbc:mysql://localhost:3306/formationspringkantra?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

#configuration de jpa/hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#configuration du serveur
server.port=8085